// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepoFeedback360.Model;

#nullable disable

namespace RepoFeedback360.Migrations
{
    [DbContext(typeof(UserDetailContext))]
    [Migration("20240602135051_AddedNewTAble")]
    partial class AddedNewTAble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RepoFeedback360.Model.DL_OTPModel", b =>
                {
                    b.Property<string>("User_ID_ForOTP")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User_Id_OTP");

                    b.Property<int>("OTP")
                        .HasColumnType("int");

                    b.Property<DateTime>("OTP_SEND_TIMESTAMP")
                        .HasColumnType("datetime2");

                    b.HasKey("User_ID_ForOTP");

                    b.ToTable("tbl_OTP_Details");
                });

            modelBuilder.Entity("RepoFeedback360.Model.FEEDBACKRATINGS", b =>
                {
                    b.Property<int>("FeedbackRatings_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackRatings_ID"));

                    b.Property<string>("BYID_EmplyeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BY_ID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Q_ID")
                        .HasColumnType("int");

                    b.Property<int>("Ratings")
                        .HasColumnType("int");

                    b.Property<string>("TOID_EmplyeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("To_ID");

                    b.HasKey("FeedbackRatings_ID");

                    b.ToTable("TBL_FEEDBACKRATINGS");
                });

            modelBuilder.Entity("RepoFeedback360.Model.FeedBackCatagoryML", b =>
                {
                    b.Property<int>("Catagory_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Catagory_ID"));

                    b.Property<string>("Catagory_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CatagryDescription");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Catagory_ID");

                    b.ToTable("tbl_FeedbackCatagory");
                });

            modelBuilder.Entity("RepoFeedback360.Model.FeedBackQuestions", b =>
                {
                    b.Property<int>("Question_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Q_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Question_Id"));

                    b.Property<int>("DESIGNATION_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Question_LongName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Question_Id");

                    b.ToTable("_dbFeedbackQuestions");
                });

            modelBuilder.Entity("RepoFeedback360.Model.FeedBackSchedulerML", b =>
                {
                    b.Property<int>("FeedSchedulerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedSchedulerID"));

                    b.Property<string>("By_EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeebBack_CatagoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("To_EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedSchedulerID");

                    b.ToTable("tbl_FeedBackScheduleDetails");
                });

            modelBuilder.Entity("RepoFeedback360.Model.UserDesignationDetails", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignationId"));

                    b.Property<string>("Designation_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignationId");

                    b.ToTable("UserDesignationDetails");
                });

            modelBuilder.Entity("RepoFeedback360.Model.UserDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("RepoFeedback360.Model.UserRoleDetails", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Role_Id"));

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_Id");

                    b.ToTable("UserRoleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
